# Autogenerated config.py
# Documentation:
#   qute://help/configuring.html
#   qute://help/settings.html

# Uncomment this to still load settings configured via autoconfig.yml
# config.load_autoconfig()

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, 'file://*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, 'chrome://*/*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, 'qute://*/*')



c.tabs.show = 'switching'

config.bind('xs', 'config-cycle statusbar.show always never')

c.colors.tabs.selected.even.bg = '#686868'
c.colors.tabs.selected.odd.bg = '#686868'
c.colors.tabs.even.bg = '#212121'
c.colors.tabs.odd.bg = '#212121'
c.colors.tabs.bar.bg = '#1c1f34'

c.colors.statusbar.command.bg = '#212121'
c.colors.statusbar.passthrough.bg = '#34426f'
c.colors.statusbar.insert.bg = '#2e2e2e'
c.colors.statusbar.insert.fg = 'white'
c.colors.statusbar.normal.bg = '#212121'

c.colors.messages.info.bg = '#282c34'

c.colors.downloads.bar.bg = '#282c34'

